export const scenes=[{name:'Janela chuvosa',desc:'Conversa boa combina com chuva.',icon:'rain'},{name:'Fim de tarde',desc:'Luz baixa, ideias altas.',icon:'sun'},{name:'Jardim tranquilo',desc:'Mais calma para o que importa.',icon:'leaf'}];
export const questions=['Qual foi a pequena alegria da sua semana?','O que aconteceu e você ainda não me contou?','Que lugar você queria me mostrar?','Qual lembrança nossa merece um replay?','O que anda ocupando a sua cabeça?','Qual coisa simples você redescobriu?','Que música combina com o seu momento?','Qual plano você está guardando com carinho?','O que você gostaria de aprender comigo?','Qual foi a melhor conversa dos últimos dias?','Do que você está precisando agora?','O que a gente podia fazer junto em breve?'];
export const rituals=[
{title:'Um gole, uma novidade',short:'Todo encontro é uma chance de descobrir algo novo.',instruction:'Cada pessoa conta uma novidade boa e uma coisa difícil. Um gole entre as histórias. Quem escuta pode só acolher.',icon:'coffee'},
{title:'Perguntas de guardanapo',short:'Temas leves e profundos para conversas que importam.',instruction:'Uma pergunta de cada vez. Vale responder, passar ou deixar o assunto tomar outro rumo.',icon:'note'},
{title:'Só fazer companhia',short:'Sem pressa. Sem roteiro. Apenas boas pessoas.',instruction:'Podem ler, desenhar ou ficar em silêncio. Estar junto já é o encontro.',icon:'leaf'},
{title:'Museu da semana',short:'Um objeto, uma história para contar.',instruction:'Cada pessoa traz um objeto que esteve na sua semana. Mostre pela câmera e conte por que ele veio à mesa.',icon:'spark'},
{title:'Café de outro lugar',short:'Duas janelas, um encontro.',instruction:'Mostre a vista daí ou descreva um lugar da sua cidade. O outro escolhe o que gostaria de conhecer.',icon:'sun'},
{title:'Carta para o próximo café',short:'Um assunto bom para continuar depois.',instruction:'Cada pessoa conta o que espera viver até o próximo encontro. Combinem quando querem conversar de novo.',icon:'note'},
{title:'Pense com o pés',short:'Uma caminhada, duas pessoas, ideias em movimento.',instruction:'Cada um caminha por um lugar tranquilo, em áudio e no seu ritmo, como num passeio peripatético. Deixem uma ideia encontrar a outra. “Pense com o pés” — Kaiury, Krow System.',icon:'leaf'}];
